spring.application.name=customerservice

server.port=8082
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.datasource.url=jdbc:postgresql://ep-broad-band-az3nu2bn-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FOEmQetoS3T9
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true